### ISSUE TITLE
그리드 셀의 내용이 많을때 전체 표시하는 방법

### ISSUE THREAD

**Issue by tnqkrzmfla** [axisj/axisj#698]
데이터 로그파일의 내용을 한 셀에 넣으려고 합니다. 
대체로 내용이 셀의 크기보다 많아 넘칠땐 ··· 처럼 말줄임으로 표시되어 셀을 늘려야 모든 내용을 볼 수 있는데 셀 안에서 셀크기를 넘어가면 자동으로 줄바꿈 될 수 있을까요? 

ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ···

대신 

ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ
ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ
ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ

처럼 표시될 수 있을지 궁금합니다.

**Comment by hyunjun19** [comment]
그 부분은 CSS로 해결하시면 됩니다.

```css
.AXGrid .AXgridScrollBody .AXGridBody .gridBodyTable tbody tr td .bodyTdText,
.AXGrid .AXgridScrollBody .AXGridBody .gridBodyTable tfoot tr td .bodyTdText,
.AXGrid .AXgridScrollBody .AXGridBody .gridBodyTable thead tr td .bodyTdText {
    white-space: pre-wrap;
}
```
