### ISSUE TITLE
AXgrid에서 그리드 안 내용이 길때 자동으로 줄바꿈 적용방법 문의

### ISSUE THREAD

**Issue by bloodiel** [axisj/axisj#855]
안녕하세요 자바스크립트를 배우고 있는 학생입니다.

AXgrid에서 그리드 안 내용이 길때 "..."으로 표현되는데 너무 길어서 자동으로 줄바꿈하여 보여주고 싶은데 자동으로 줄바꿈 되게 할수 있는 기능이 있나요?

예제들을 모두 살펴 봤는데 못찾겠어서 문으 드립니다.

**Comment by hyunjun19** [comment]
CSS로 해결하시면 됩니다.

```css
.ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

```js
...
        colGroup : [ // 데이터 리스트의 컬럼을 정의합니다.
        {
            key      : "no",        // {String} -- 데이터와 맵핑할 키 입니다. key 명칭은 reservedKey
            label    : "번호",      // {String} -- 사용자에게 보여줄 컬럼명입니다.
            addClass: function(){
                return "ellipsis";
            }
        }
    ],
...
```
